### ISSUE TITLE
lol

### ISSUE THREAD

**Issue by slavserver** [etclabscore/etchash#4]
hello ... remember ubiqhash and how it fell in price ... you would like only video cards to be mining ... and what, your coin went to the bottom ...
Now imagine, you are doing etchash, you are planning to attract 3 gigabytes, 4 gigabytes of video cards to mining .... and what's the point? these video cards, compared to modern ones, consume more electricity ... a modern 8 gigabyte card consumes 70 watts .... while older cards consume 150-180 watts of energy ... you as ubiqhash destroy the coin .... you were asked - pirlguard
_____________________________________

привет... вспомните ubiqhash икак он упал в цене..... вы, хотели, что бы майнингом занимались только видеокарты..... и что, ваша монета ушла на дно....
а теперь представьтье, вы делаете etchash , вы планируте привлечь к майнингу видеокарты 3 гигабата, 4 гигабайта.... а в чем смысл? эти видео карты, по сравнению с современныменными, потребляют больше электричичесва..... современная карта на 8 гигабайт, потребляет 70 ватт.... в то время как более древние карты потребляют 150- 180 ватт энергиии.... вы, как ubiqhash уничтожите монету.... вам было предложено - pirlguard

**Comment by nenastupi** [comment]
+1
against algorithm change

**Comment by meowsbits** [comment]
For discussion on ECIP1099, please use https://github.com/ethereumclassic/ECIPs/issues/368.
